# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sajal/fighter-plane

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sajal/fighter-plane

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sajal/fighter-plane/CMakeFiles /home/sajal/fighter-plane/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sajal/fighter-plane/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphics_asgn1

# Build rule for target.
graphics_asgn1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graphics_asgn1
.PHONY : graphics_asgn1

# fast build rule for target.
graphics_asgn1/fast:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/build
.PHONY : graphics_asgn1/fast

src/aim.o: src/aim.cpp.o

.PHONY : src/aim.o

# target to build an object file
src/aim.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/aim.cpp.o
.PHONY : src/aim.cpp.o

src/aim.i: src/aim.cpp.i

.PHONY : src/aim.i

# target to preprocess a source file
src/aim.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/aim.cpp.i
.PHONY : src/aim.cpp.i

src/aim.s: src/aim.cpp.s

.PHONY : src/aim.s

# target to generate assembly for a file
src/aim.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/aim.cpp.s
.PHONY : src/aim.cpp.s

src/arrow.o: src/arrow.cpp.o

.PHONY : src/arrow.o

# target to build an object file
src/arrow.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/arrow.cpp.o
.PHONY : src/arrow.cpp.o

src/arrow.i: src/arrow.cpp.i

.PHONY : src/arrow.i

# target to preprocess a source file
src/arrow.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/arrow.cpp.i
.PHONY : src/arrow.cpp.i

src/arrow.s: src/arrow.cpp.s

.PHONY : src/arrow.s

# target to generate assembly for a file
src/arrow.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/arrow.cpp.s
.PHONY : src/arrow.cpp.s

src/bomb.o: src/bomb.cpp.o

.PHONY : src/bomb.o

# target to build an object file
src/bomb.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/bomb.cpp.o
.PHONY : src/bomb.cpp.o

src/bomb.i: src/bomb.cpp.i

.PHONY : src/bomb.i

# target to preprocess a source file
src/bomb.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/bomb.cpp.i
.PHONY : src/bomb.cpp.i

src/bomb.s: src/bomb.cpp.s

.PHONY : src/bomb.s

# target to generate assembly for a file
src/bomb.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/bomb.cpp.s
.PHONY : src/bomb.cpp.s

src/bullet.o: src/bullet.cpp.o

.PHONY : src/bullet.o

# target to build an object file
src/bullet.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/bullet.cpp.o
.PHONY : src/bullet.cpp.o

src/bullet.i: src/bullet.cpp.i

.PHONY : src/bullet.i

# target to preprocess a source file
src/bullet.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/bullet.cpp.i
.PHONY : src/bullet.cpp.i

src/bullet.s: src/bullet.cpp.s

.PHONY : src/bullet.s

# target to generate assembly for a file
src/bullet.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/bullet.cpp.s
.PHONY : src/bullet.cpp.s

src/color.o: src/color.cpp.o

.PHONY : src/color.o

# target to build an object file
src/color.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/color.cpp.o
.PHONY : src/color.cpp.o

src/color.i: src/color.cpp.i

.PHONY : src/color.i

# target to preprocess a source file
src/color.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/color.cpp.i
.PHONY : src/color.cpp.i

src/color.s: src/color.cpp.s

.PHONY : src/color.s

# target to generate assembly for a file
src/color.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/color.cpp.s
.PHONY : src/color.cpp.s

src/compass.o: src/compass.cpp.o

.PHONY : src/compass.o

# target to build an object file
src/compass.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/compass.cpp.o
.PHONY : src/compass.cpp.o

src/compass.i: src/compass.cpp.i

.PHONY : src/compass.i

# target to preprocess a source file
src/compass.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/compass.cpp.i
.PHONY : src/compass.cpp.i

src/compass.s: src/compass.cpp.s

.PHONY : src/compass.s

# target to generate assembly for a file
src/compass.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/compass.cpp.s
.PHONY : src/compass.cpp.s

src/compass_needle.o: src/compass_needle.cpp.o

.PHONY : src/compass_needle.o

# target to build an object file
src/compass_needle.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/compass_needle.cpp.o
.PHONY : src/compass_needle.cpp.o

src/compass_needle.i: src/compass_needle.cpp.i

.PHONY : src/compass_needle.i

# target to preprocess a source file
src/compass_needle.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/compass_needle.cpp.i
.PHONY : src/compass_needle.cpp.i

src/compass_needle.s: src/compass_needle.cpp.s

.PHONY : src/compass_needle.s

# target to generate assembly for a file
src/compass_needle.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/compass_needle.cpp.s
.PHONY : src/compass_needle.cpp.s

src/display.o: src/display.cpp.o

.PHONY : src/display.o

# target to build an object file
src/display.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/display.cpp.o
.PHONY : src/display.cpp.o

src/display.i: src/display.cpp.i

.PHONY : src/display.i

# target to preprocess a source file
src/display.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/display.cpp.i
.PHONY : src/display.cpp.i

src/display.s: src/display.cpp.s

.PHONY : src/display.s

# target to generate assembly for a file
src/display.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/display.cpp.s
.PHONY : src/display.cpp.s

src/enemy.o: src/enemy.cpp.o

.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i

.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s

.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/enemy_arrow.o: src/enemy_arrow.cpp.o

.PHONY : src/enemy_arrow.o

# target to build an object file
src/enemy_arrow.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/enemy_arrow.cpp.o
.PHONY : src/enemy_arrow.cpp.o

src/enemy_arrow.i: src/enemy_arrow.cpp.i

.PHONY : src/enemy_arrow.i

# target to preprocess a source file
src/enemy_arrow.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/enemy_arrow.cpp.i
.PHONY : src/enemy_arrow.cpp.i

src/enemy_arrow.s: src/enemy_arrow.cpp.s

.PHONY : src/enemy_arrow.s

# target to generate assembly for a file
src/enemy_arrow.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/enemy_arrow.cpp.s
.PHONY : src/enemy_arrow.cpp.s

src/fuel_point.o: src/fuel_point.cpp.o

.PHONY : src/fuel_point.o

# target to build an object file
src/fuel_point.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/fuel_point.cpp.o
.PHONY : src/fuel_point.cpp.o

src/fuel_point.i: src/fuel_point.cpp.i

.PHONY : src/fuel_point.i

# target to preprocess a source file
src/fuel_point.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/fuel_point.cpp.i
.PHONY : src/fuel_point.cpp.i

src/fuel_point.s: src/fuel_point.cpp.s

.PHONY : src/fuel_point.s

# target to generate assembly for a file
src/fuel_point.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/fuel_point.cpp.s
.PHONY : src/fuel_point.cpp.s

src/ground.o: src/ground.cpp.o

.PHONY : src/ground.o

# target to build an object file
src/ground.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ground.cpp.o
.PHONY : src/ground.cpp.o

src/ground.i: src/ground.cpp.i

.PHONY : src/ground.i

# target to preprocess a source file
src/ground.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ground.cpp.i
.PHONY : src/ground.cpp.i

src/ground.s: src/ground.cpp.s

.PHONY : src/ground.s

# target to generate assembly for a file
src/ground.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/ground.cpp.s
.PHONY : src/ground.cpp.s

src/healthbar.o: src/healthbar.cpp.o

.PHONY : src/healthbar.o

# target to build an object file
src/healthbar.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/healthbar.cpp.o
.PHONY : src/healthbar.cpp.o

src/healthbar.i: src/healthbar.cpp.i

.PHONY : src/healthbar.i

# target to preprocess a source file
src/healthbar.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/healthbar.cpp.i
.PHONY : src/healthbar.cpp.i

src/healthbar.s: src/healthbar.cpp.s

.PHONY : src/healthbar.s

# target to generate assembly for a file
src/healthbar.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/healthbar.cpp.s
.PHONY : src/healthbar.cpp.s

src/input.o: src/input.cpp.o

.PHONY : src/input.o

# target to build an object file
src/input.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/input.cpp.o
.PHONY : src/input.cpp.o

src/input.i: src/input.cpp.i

.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s

.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/missile.o: src/missile.cpp.o

.PHONY : src/missile.o

# target to build an object file
src/missile.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/missile.cpp.o
.PHONY : src/missile.cpp.o

src/missile.i: src/missile.cpp.i

.PHONY : src/missile.i

# target to preprocess a source file
src/missile.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/missile.cpp.i
.PHONY : src/missile.cpp.i

src/missile.s: src/missile.cpp.s

.PHONY : src/missile.s

# target to generate assembly for a file
src/missile.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/missile.cpp.s
.PHONY : src/missile.cpp.s

src/mountain.o: src/mountain.cpp.o

.PHONY : src/mountain.o

# target to build an object file
src/mountain.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/mountain.cpp.o
.PHONY : src/mountain.cpp.o

src/mountain.i: src/mountain.cpp.i

.PHONY : src/mountain.i

# target to preprocess a source file
src/mountain.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/mountain.cpp.i
.PHONY : src/mountain.cpp.i

src/mountain.s: src/mountain.cpp.s

.PHONY : src/mountain.s

# target to generate assembly for a file
src/mountain.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/mountain.cpp.s
.PHONY : src/mountain.cpp.s

src/needle.o: src/needle.cpp.o

.PHONY : src/needle.o

# target to build an object file
src/needle.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/needle.cpp.o
.PHONY : src/needle.cpp.o

src/needle.i: src/needle.cpp.i

.PHONY : src/needle.i

# target to preprocess a source file
src/needle.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/needle.cpp.i
.PHONY : src/needle.cpp.i

src/needle.s: src/needle.cpp.s

.PHONY : src/needle.s

# target to generate assembly for a file
src/needle.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/needle.cpp.s
.PHONY : src/needle.cpp.s

src/nonedit.o: src/nonedit.cpp.o

.PHONY : src/nonedit.o

# target to build an object file
src/nonedit.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/nonedit.cpp.o
.PHONY : src/nonedit.cpp.o

src/nonedit.i: src/nonedit.cpp.i

.PHONY : src/nonedit.i

# target to preprocess a source file
src/nonedit.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/nonedit.cpp.i
.PHONY : src/nonedit.cpp.i

src/nonedit.s: src/nonedit.cpp.s

.PHONY : src/nonedit.s

# target to generate assembly for a file
src/nonedit.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/nonedit.cpp.s
.PHONY : src/nonedit.cpp.s

src/other_handlers.o: src/other_handlers.cpp.o

.PHONY : src/other_handlers.o

# target to build an object file
src/other_handlers.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/other_handlers.cpp.o
.PHONY : src/other_handlers.cpp.o

src/other_handlers.i: src/other_handlers.cpp.i

.PHONY : src/other_handlers.i

# target to preprocess a source file
src/other_handlers.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/other_handlers.cpp.i
.PHONY : src/other_handlers.cpp.i

src/other_handlers.s: src/other_handlers.cpp.s

.PHONY : src/other_handlers.s

# target to generate assembly for a file
src/other_handlers.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/other_handlers.cpp.s
.PHONY : src/other_handlers.cpp.s

src/parachute.o: src/parachute.cpp.o

.PHONY : src/parachute.o

# target to build an object file
src/parachute.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/parachute.cpp.o
.PHONY : src/parachute.cpp.o

src/parachute.i: src/parachute.cpp.i

.PHONY : src/parachute.i

# target to preprocess a source file
src/parachute.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/parachute.cpp.i
.PHONY : src/parachute.cpp.i

src/parachute.s: src/parachute.cpp.s

.PHONY : src/parachute.s

# target to generate assembly for a file
src/parachute.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/parachute.cpp.s
.PHONY : src/parachute.cpp.s

src/plane.o: src/plane.cpp.o

.PHONY : src/plane.o

# target to build an object file
src/plane.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/plane.cpp.o
.PHONY : src/plane.cpp.o

src/plane.i: src/plane.cpp.i

.PHONY : src/plane.i

# target to preprocess a source file
src/plane.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/plane.cpp.i
.PHONY : src/plane.cpp.i

src/plane.s: src/plane.cpp.s

.PHONY : src/plane.s

# target to generate assembly for a file
src/plane.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/plane.cpp.s
.PHONY : src/plane.cpp.s

src/rings.o: src/rings.cpp.o

.PHONY : src/rings.o

# target to build an object file
src/rings.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/rings.cpp.o
.PHONY : src/rings.cpp.o

src/rings.i: src/rings.cpp.i

.PHONY : src/rings.i

# target to preprocess a source file
src/rings.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/rings.cpp.i
.PHONY : src/rings.cpp.i

src/rings.s: src/rings.cpp.s

.PHONY : src/rings.s

# target to generate assembly for a file
src/rings.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/rings.cpp.s
.PHONY : src/rings.cpp.s

src/speedbar.o: src/speedbar.cpp.o

.PHONY : src/speedbar.o

# target to build an object file
src/speedbar.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/speedbar.cpp.o
.PHONY : src/speedbar.cpp.o

src/speedbar.i: src/speedbar.cpp.i

.PHONY : src/speedbar.i

# target to preprocess a source file
src/speedbar.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/speedbar.cpp.i
.PHONY : src/speedbar.cpp.i

src/speedbar.s: src/speedbar.cpp.s

.PHONY : src/speedbar.s

# target to generate assembly for a file
src/speedbar.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/speedbar.cpp.s
.PHONY : src/speedbar.cpp.s

src/speedometer.o: src/speedometer.cpp.o

.PHONY : src/speedometer.o

# target to build an object file
src/speedometer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/speedometer.cpp.o
.PHONY : src/speedometer.cpp.o

src/speedometer.i: src/speedometer.cpp.i

.PHONY : src/speedometer.i

# target to preprocess a source file
src/speedometer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/speedometer.cpp.i
.PHONY : src/speedometer.cpp.i

src/speedometer.s: src/speedometer.cpp.s

.PHONY : src/speedometer.s

# target to generate assembly for a file
src/speedometer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/speedometer.cpp.s
.PHONY : src/speedometer.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/graphics_asgn1.dir/build.make CMakeFiles/graphics_asgn1.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... graphics_asgn1"
	@echo "... edit_cache"
	@echo "... src/aim.o"
	@echo "... src/aim.i"
	@echo "... src/aim.s"
	@echo "... src/arrow.o"
	@echo "... src/arrow.i"
	@echo "... src/arrow.s"
	@echo "... src/bomb.o"
	@echo "... src/bomb.i"
	@echo "... src/bomb.s"
	@echo "... src/bullet.o"
	@echo "... src/bullet.i"
	@echo "... src/bullet.s"
	@echo "... src/color.o"
	@echo "... src/color.i"
	@echo "... src/color.s"
	@echo "... src/compass.o"
	@echo "... src/compass.i"
	@echo "... src/compass.s"
	@echo "... src/compass_needle.o"
	@echo "... src/compass_needle.i"
	@echo "... src/compass_needle.s"
	@echo "... src/display.o"
	@echo "... src/display.i"
	@echo "... src/display.s"
	@echo "... src/enemy.o"
	@echo "... src/enemy.i"
	@echo "... src/enemy.s"
	@echo "... src/enemy_arrow.o"
	@echo "... src/enemy_arrow.i"
	@echo "... src/enemy_arrow.s"
	@echo "... src/fuel_point.o"
	@echo "... src/fuel_point.i"
	@echo "... src/fuel_point.s"
	@echo "... src/ground.o"
	@echo "... src/ground.i"
	@echo "... src/ground.s"
	@echo "... src/healthbar.o"
	@echo "... src/healthbar.i"
	@echo "... src/healthbar.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/missile.o"
	@echo "... src/missile.i"
	@echo "... src/missile.s"
	@echo "... src/mountain.o"
	@echo "... src/mountain.i"
	@echo "... src/mountain.s"
	@echo "... src/needle.o"
	@echo "... src/needle.i"
	@echo "... src/needle.s"
	@echo "... src/nonedit.o"
	@echo "... src/nonedit.i"
	@echo "... src/nonedit.s"
	@echo "... src/other_handlers.o"
	@echo "... src/other_handlers.i"
	@echo "... src/other_handlers.s"
	@echo "... src/parachute.o"
	@echo "... src/parachute.i"
	@echo "... src/parachute.s"
	@echo "... src/plane.o"
	@echo "... src/plane.i"
	@echo "... src/plane.s"
	@echo "... src/rings.o"
	@echo "... src/rings.i"
	@echo "... src/rings.s"
	@echo "... src/speedbar.o"
	@echo "... src/speedbar.i"
	@echo "... src/speedbar.s"
	@echo "... src/speedometer.o"
	@echo "... src/speedometer.i"
	@echo "... src/speedometer.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

